### ISSUE TITLE
Feign Death Not Working

### ISSUE THREAD

**Issue by armchairrockstar1** [Cortes-Jeremy/SoundAlerter#12]
Hunter's Feign Death (Under "Enemy Cooldown Abilities") doesn't trigger a sound when hunters use it in PvP.

Please fix if you can.

Ty for this awesome addon anyway.

**Comment by Cortes-Jeremy** [comment]
Yo, 
I dont play anymore, 
this event should not work unless the server is badly scripted,
as I remember when hes doing feign death the event sended to the client is a death event and not a spell casted with and id as argument.
I think I let the spell on the addon cause I was thinking of a workaround but never implemented it.

Cheers.
